# Generated by Django 4.2.3 on 2023-11-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionText',
            new_name='questionId',
        ),
    ]
