# Generated by Django 4.2.3 on 2023-11-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_questiontext_question_questionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionId',
            new_name='questionText',
        ),
    ]
